### ISSUE TITLE
download scheduled talk as an vEvent/iCalendar

### ISSUE THREAD

**Issue by smoench** [tolry/talkly#58]

**Comment by tolry** [comment]
Will you pick up this task? Otherwise I would volunteer.

**Comment by larsborn** [comment]
Some Outlook appoinment via email support would be supergreat!

**Comment by tolry** [comment]
@larsborn good idea, but I have my doubts about the ending up confusing the users: outlook event invitations have a back channel, i.e. the receiver can respond with positive/negative/uncertain.

Either we implement this, which is lots of hassle server administration wise (forward email address to a script) or we ignore it (dead e-mail address? spam speaker's inbox). In the later case the user might get frustrated since there is an interaction possiblity, but it is completely ignored.

But perhaps we just might need to experiment with it, since other e-mail applications (e.g. gmail) also support this.

**Comment by tolry** [comment]
this might also be a possible solution https://addtocalendar.com/
