### ISSUE TITLE
URL detection might be a bit broken

### ISSUE THREAD

**Issue by larsborn** [tolry/talkly#64]
If you write something like http://queues.io/) in a comment, the links includes the closing bracket.

**Comment by tolry** [comment]
thx for the report, we are using "kzykhys/ciconia" for markdown rendering - maybe there is a fix for that already or we could contribute

**Comment by DavidBadura** [comment]
kzykhys/ciconia are not maintained anymore :-( see https://github.com/kzykhys/Ciconia/issues/52

**Comment by tolry** [comment]
right, we should switch to commonmark, should be more or less drop-in-replacement

**Comment by DavidBadura** [comment]
which commonmark? :D

**Comment by tolry** [comment]
https://github.com/fluxbb/commonmark should be very close to our current library since it's the inofficial follow up. But it seems as if it's not that popular yet.

In regard to popularity, the php league's implementation seems to be king right now https://github.com/search?l=PHP&q=commonmark&type=Repositories&utf8=%E2%9C%93

**Comment by DavidBadura** [comment]
see #70
